### ISSUE TITLE
Points not showing correctly

### ISSUE THREAD

**Issue by Alaedar** [andrelind/launch-bay-next-web#26]
**Describe the bug**
My list was 203 pts on phone app but shows a 198 on navigator

**To Reproduce**
Go here : **https://launchbaynext.app/?lbx=%27AXAX%27.198.4.0.l54.436.l1.471r.l19.460rr.l53.419.l18.486r.l1.471rr.l53.420.l18.486r.l1.471rr.l54.638.l1.471r.l19.460rr**

44 + 55 + 56 +48 does 203 and not 198
**Expected behavior**
Should appear at 203

**Screenshots**
![image](https://user-images.githubusercontent.com/77126569/104322550-6396c000-54e5-11eb-99cf-5dcabf550a01.png)

**Desktop (please complete the following information):**
 Windows
Mozilla
Dunno the version

**Additional context**
Thanks for the hard word !

**Comment by andrelind** [comment]
Should be fixed now 😊
