### ISSUE TITLE
Screen goes to white when deleting the list you are currently editing.

### ISSUE THREAD

**Issue by peterkejser** [andrelind/launch-bay-next-web#27]
**Describe the bug**
While I am editing a squadron, if I open the Squadron list and delete the list that I am currently working on, the entire screen goes white, and I have to reload the webpage.

**To Reproduce**
1. Enter website.
2. Log in with google account.
3. Open Squadrons List.
4. Find a Rebel squadron called "New Squadron" worth 0 points, which you are currently editing. 
5. Delete that list.
5. Screen goes entirely white.

**Expected behavior**
The list should be deleted, and I expected to be returned to a landing screen, where I could select a faction to start a new squadron.

**Screenshots**
![image](https://user-images.githubusercontent.com/14195245/104325821-524fb280-54e9-11eb-9ee0-68dca090e664.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 87.0.4280.141 (Official Build) (64-bit)

**Comment by andrelind** [comment]
Should be fixed now 😊

**Comment by peterkejser** [comment]
Yep, also works on my end. Your work continues to impress :D
