### ISSUE TITLE
Blank page when deleting loaded squad

### ISSUE THREAD

**Issue by Rellik7** [andrelind/launch-bay-next-web#29]
**Describe the bug**
When deleting the squadron that is currently loaded the page turns blank and when pressing to reload all previous changes are undone

**To Reproduce**
1. Select a new squadron or edit an existing one
2. Click on squadrons 
3. Scroll down to the loaded squadron and click in the bin to delete
4. The page will become blank

**Expected behavior**
That the squadron get deleted and the current page goes to a main page or that a warning is displayed asking to select another squadron then delete the current one

**Desktop:**
 - OS: Windows 10 v19041.685
 - Browser: Mozilla Firefox
 - Version: 84.0.2

**Comment by andrelind** [comment]
Should be fixed now 😊
