### ISSUE TITLE
Missing Epic Upgrade for B-Wing

### ISSUE THREAD

**Issue by dwx0613** [andrelind/launch-bay-next-web#42]
The B6 Blade Wing Prototype title/command card isn't listed as an option for the B-Wing. There is also a second Phoenix Squadron command upgrade listed for 200 points.

The Epic B6 card adds a gunner slot and also states:

Attack (Action: Lock): Gain 1 ion token to perform this attack. If this attack hits, the defender suffers 1 additional Hit/Critical Hit damage for each matching uncancelled result after the first.

**Comment by andrelind** [comment]
Fixed :-)
