### ISSUE TITLE
[Using Chrome] Jedi General is missing in ETA-2 pilot selection

### ISSUE THREAD

**Issue by peterkejser** [andrelind/launch-bay-next-web#53]
EDIT: PLEASE IGNORE AND CLOSE IMMEDIATELY. USER ERROR. ASSUMED NEW SQUADRON ON DESKTOP WOULD DEFAULT TO EXTENDED FORMAT. HOWEVER IT WAS IN HYPERSPACE, WHERE JEDI GENERAL ISN'T ALLOWED. THERE IS NO PROBLEM.

**Describe the bug**
When I use the dropdown menu to choose which pilot I want to put in my ETA-2 Actis, the Jedi general pilot is missing. Checked with the android version, and the Jedi General is only missing when using Chrome.

**To Reproduce**
1. Make now Republic squad
2. Make first ship an ETA-2 Actis
3. Use dropdown to select which pilot you want.

**Expected behavior**
I expected the Jedi General to be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/14195245/118393676-8e825380-b640-11eb-9610-7b3a1b6b396f.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro Version 10.0.19041 Build 19041
 - Browser: Chrome
 - Version: 90.0.4430.212 (Official Build) (64-bit)

**Comment by andrelind** [comment]
Hi!

This is due to Hyperspace being selected as default for new squadrons, I'll change the default setting :-)

// André
